#pragma config(Motor,  port2,           motor1,        tmotorVex393, openLoop)
#pragma config(Motor,  port3,           motor2,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           motor3,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           motor4,        tmotorVex393, openLoop)
#pragma config(Motor,  port6,           motor5,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           motor6,        tmotorVex393, openLoop)
#pragma config(Motor,  port8,           motor7,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           motor8,        tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motor1] = 127;
	motor[motor2] = 127;
	motor[motor3] = 127;
	motor[motor4] = 127;
	motor[motor5] = 127;
	motor[motor6] = 127;
	motor[motor7] = 127;
	motor[motor8] = 127;

	Sleep(5000);

}
