#pragma config(Sensor, in3,    Line1,          sensorLineFollower)
#pragma config(Sensor, in4,    Line2,          sensorLineFollower)
#pragma config(Sensor, in5,    Line3,          sensorLineFollower)
#pragma config(Sensor, in6,    Arm,            sensorPotentiometer)
#pragma config(Sensor, in7,    Ambient,        sensorReflection)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  Bump,           sensorTouch)
#pragma config(Sensor, dgtl7,  ClawLimit,      sensorTouch)
#pragma config(Sensor, dgtl11, SonarIn,        sensorSONAR_cm)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           clawMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void bothMotors(int value){
	motor[leftMotor] = value;
	motor[rightMotor] = value;
}
void drive(float length){//Tharf ad setja tad inn ad hann keyrir beint
	float value = length * 1650;
	bothMotors(100);
	Sleep(value);
	bothMotors(0);
}
void resetEncoders(){
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;
}
void rotate(float gradurInn){

	float degrees = gradurInn;

	float distance = (1035*(degrees/360));

	resetEncoders();

	if(distance > 0){
		while(abs(SensorValue[rightEncoder]) < abs(distance)) // While the right encoder is less than distance:
	  {
	    motor[rightMotor] = -63;         //* Run both motors
	    motor[leftMotor]  = 63;         //* forward at half speed.
	    if(abs(SensorValue[rightEncoder]) > abs(SensorValue[leftEncoder])){
	    	while(abs(SensorValue[rightEncoder]) > abs(SensorValue[leftEncoder]) && abs(SensorValue[rightEncoder]) < abs(distance)){
	    		motor[leftMotor] = 70;
	    	}
	    }
	    else if(abs(SensorValue[rightEncoder]) < abs(SensorValue[leftEncoder])){
	    	while(abs(SensorValue[rightEncoder]) < abs(SensorValue[leftEncoder]) && abs(SensorValue[rightEncoder]) < abs(distance)){
	    		motor[rightMotor] = -70;
	    	}
	    }
	  }
	}
	else if (distance < 0){
		while(abs(SensorValue[leftEncoder]) < abs(distance)) // While the right encoder is less than distance:
	  {
	    motor[rightMotor] = 63;         // Run both motors
	    motor[leftMotor]  = -63;         //forward at half speed.

	    if(abs(SensorValue[rightEncoder]) > abs(SensorValue[leftEncoder])){
	    	while(abs(SensorValue[rightEncoder]) > abs(SensorValue[leftEncoder]) && abs(SensorValue[rightEncoder]) < abs(distance)){
	    		motor[leftMotor] = -70;
	    	}
	    }
	    else if(abs(SensorValue[rightEncoder]) < abs(SensorValue[leftEncoder])){
	    	while(abs(SensorValue[rightEncoder]) < abs(SensorValue[leftEncoder]) && abs(SensorValue[rightEncoder]) < abs(distance)){
	    		motor[rightMotor] = 70;
	    	}
	    }
	  }
	}
  bothMotors(0);
}


bool between(int low, int num, int high){
	if(low < num && num < high){
		return true;
	}
	else{
		return false;
	}
}
//1035 = heill hringur
//1650 = 1m afram

task main()
{
	while(true){
		/*int num1 = SensorValue[Line1];//haegri
		int num2 = SensorValue[Line2];
		int num3 = SensorValue[Line3];//vinstri
		//2950 ish = lina
		//2800-2900 = ekki lina
		*/
		while(between(2930, SensorValue[Line2], 2970)){
			bothMotors(40);//mean tad er svart undir midjunni
		}
		if(between(2930, SensorValue[Line1], 2970)){
			//ef tad er lina hagra meginn
			while(SensorValue[Line2] != 2950){
				motor[leftMotor] = 30;
				motor[rightMotor] = 0;
			}
			bothMotors(-10);
			Sleep(20);
			bothMotors(0);
		}
		else if(SensorValue[Line2] != 2950){
			//ef tad er lina vinstra megin
			while(between(2930, SensorValue[Line2], 2970) == false){
				motor[leftMotor] = 0;
				motor[rightMotor] = 30;
			}
			bothMotors(-10);
			Sleep(20);
			bothMotors(0);
		}
		else{
			//a aldrei ad koma hingad fml
			//bakka?
			bothMotors(-10);
			//lat hann bakka her sem debug feature
		}
	}
}
