#pragma config(Sensor, in3,    Line1,          sensorLineFollower)
#pragma config(Sensor, in4,    Line2,          sensorLineFollower)
#pragma config(Sensor, in5,    Line3,          sensorLineFollower)
#pragma config(Sensor, in6,    Arm,            sensorPotentiometer)
#pragma config(Sensor, in7,    Ambient,        sensorReflection)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  clawLimit,      sensorTouch)
#pragma config(Sensor, dgtl11, SonarIn,        sensorSONAR_cm)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           clawMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void bothMotors(int value){
	motor[leftMotor] = value;
	motor[rightMotor] = value;
}
void drive(float length){//Tharf ad setja tad inn ad hann keyrir beint
	float value = length * 1650;
	bothMotors(100);
	Sleep(value);
	bothMotors(0);
}
void resetEncoders(){
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;
}
void rotate(float gradurInn){

	float degrees = gradurInn;

	float distance = (1035*(degrees/360));

	resetEncoders();

	if(distance > 0){
		while(abs(SensorValue[rightEncoder]) < abs(distance)) // While the right encoder is less than distance:
	  {
	    motor[rightMotor] = -63;         //* Run both motors
	    motor[leftMotor]  = 63;         //* forward at half speed.
	    if(abs(SensorValue[rightEncoder]) > abs(SensorValue[leftEncoder])){
	    	while(abs(SensorValue[rightEncoder]) > abs(SensorValue[leftEncoder]) && abs(SensorValue[rightEncoder]) < abs(distance)){
	    		motor[leftMotor] = 70;
	    	}
	    }
	    else if(abs(SensorValue[rightEncoder]) < abs(SensorValue[leftEncoder])){
	    	while(abs(SensorValue[rightEncoder]) < abs(SensorValue[leftEncoder]) && abs(SensorValue[rightEncoder]) < abs(distance)){
	    		motor[rightMotor] = -70;
	    	}
	    }
	  }
	}
	else if (distance < 0){
		while(abs(SensorValue[leftEncoder]) < abs(distance)) // While the right encoder is less than distance:
	  {
	    motor[rightMotor] = 63;         // Run both motors
	    motor[leftMotor]  = -63;         //forward at half speed.

	    if(abs(SensorValue[rightEncoder]) > abs(SensorValue[leftEncoder])){
	    	while(abs(SensorValue[rightEncoder]) > abs(SensorValue[leftEncoder]) && abs(SensorValue[rightEncoder]) < abs(distance)){
	    		motor[leftMotor] = -70;
	    	}
	    }
	    else if(abs(SensorValue[rightEncoder]) < abs(SensorValue[leftEncoder])){
	    	while(abs(SensorValue[rightEncoder]) < abs(SensorValue[leftEncoder]) && abs(SensorValue[rightEncoder]) < abs(distance)){
	    		motor[rightMotor] = 70;
	    	}
	    }
	  }
	}
  bothMotors(0);
}

bool ball(){
	if(SensorValue[SonarIn] != -1){
		return true;
	}
	else{
		return false;
	}
}

bool between(int low, int num, int high){
	if(low < num && num < high){
		return true;
	}
	else{
		return false;
	}
}
//1035 = heill hringur
//1650 = 1m afram

void lineForward(){
	drive(0.05);
}
task main()
{
	while(true){
		while(ball()==false){
			lineForward();

			if(between(2930, SensorValue[Line2], 2970)){
				//pass
			}
			else{
				if(between(2930, SensorValue[Line1], 2970)){
					while(between(2930, SensorValue[Line2], 2970) == false){
						rotate(1);
					}
				}
				else if(between(2930, SensorValue[Line3], 2970)){
					while(between(2930, SensorValue[Line2], 2970) == false){
						rotate(-1);
					}//close while
				}//close else if
			}//close else
		}//close while
		while(ball()){
			//open claw
			motor[clawMotor] = 50;
			//claw down
			while(SensorValue[clawLimit] == 0){
				motor[armMotor]=-20;
			}//close while
			motor[clawMotor] = -50;
			//close claw
			motor[armMotor] = 20;
			//claw up
		}//close while
	}//close while
}//close main
